global:
  # certificates added to this secret will be copied to $JFROG_HOME/<product>/var/etc/security/keys/trusted directory
  customCertificates:
    enabled: true
    certificateSecretName: main-root-cert                 

artifactory:
  enabled: true
  nginx:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - edge1.jfrog.pro
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_pass_header   Server;
        proxy_set_header    X-JFrog-Override-Base-Url http://edge1.jfrog.pro;

    # kubernetes.io/tls-acme: "true"
    # tls:
    # - secretName: jpd-tls 
    #   hosts:
    #     - edge1.jfrog.pro
    # Additional ingress rules
    # additionalRules: []

  artifactory:
    # Note: For HA deployments, set replicaCount >1 (recommended 3)
    replicaCount: 1
    license:
      secret: artifactory-edge-license
      dataKey: art.lic
    service:
      type: ClusterIP
    replicator:      
      enabled: true
      ingress:
        name: edge1-replication
        annotations: 
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding on;

        # tls: []
        #  Secrets must be manually created in the namespace.
        # - hosts:
        #   - artifactory.domain.example
        #   secretName: chart-example-tls-secret
      ## When replicator is enabled and want to use tracker feature, trackerIngress.enabled flag should be set to true
      ## Please refer - https://www.jfrog.com/confluence/display/JFROG/JFrog+Peer-to-Peer+%28P2P%29+Downloads
      trackerIngress:
        enabled: false
        # hosts: []
        # name: edge1-tracker
        # annotations:
        # kubernetes.io/ingress.class: nginx
        # nginx.ingress.kubernetes.io/proxy-buffering: "off"
        # nginx.ingress.kubernetes.io/configuration-snippet: |
        #   chunked_transfer_encoding on;
        # tls: []
        #  Secrets must be manually created in the namespace.
        # - hosts:
        #   - artifactory.domain.example
        #   secretName: chart-example-tls-secret

xray:
  enabled: false
insight:
  enabled: false
distribution:
  enabled: false
pipelines:
  enabled: false
redis:
  enabled: false
rabbitmq:
  enabled: false

